### PR TITLE
Expose the epoll support.

### PR DESCRIPTION
**Pull request by rodjjo**
## What
I was trying to use epoll based on this information here: [epoll syscall in WASIX](https://wasmer.io/posts/wasix-epoll). I saw that wasmer had the support, however the library does not have.

## Why
To allow the use of the epoll routines in C applications.

## Description
Here I call the equivalent functions from wasix, so I was able to use epoll in my wasm applications.

I had to pay attention to the different structures and types in order to make it work [see](https://github.com/wasix-org/wasix-libc/issues/31). That's why I had to map the enums and the structs correctly.

### CODE REVIEW

**Comment by theduke** [comment]
@rodjjo thanks!

Up to now epoll was only used from the Rust side in the `mio` / `tokio` forks, hence why it wasn't in the libc yet.

We'll review soon.

**Review by john-sharratt — CHANGES_REQUESTED** [review]
@rodjjo thanks for the contribution.

Can you run the `build64.sh` as well as the `build32.sh` script - this will give you the needed updates for the `expected/wasm64-wasi` so we have the 64bit version kept up to date.

Otherwise looks good.

**Comment by rodjjo** [comment]
Hi @john-sharratt hope you're doing well.

I changed it to fix build64.sh, do I need to do anything else ?

Thanks.

**Review by john-sharratt — APPROVED** [review]
Thanks for the contribution

**Comment by syrusakbary** [comment]
Lets merge, thanks for the contribution @rodjjo!

**Pull request merged**
