### PR TITLE
Some changes to have curl running with minimal sources changes

### PR DESCRIPTION
**Pull request by ptitSeb**
Some changes to have curl running with minimal sources changes

### CODE REVIEW

**Comment by jedisct1** [comment]
This is very cool.

Is it something you are planning to contribute to `zig cc` for general use?

**Comment by syrusakbary** [comment]
> Is it something you are planning to contribute to `zig cc` for general use?

We'd love to

**Comment by jedisct1** [comment]
0.11 is round the corner, so it's a little bit too late for that release.

But if WASIX is also useable on the web, that can be a good justification for adding it right after the release.

**Comment by codefromthecrypt** [comment]
@syrusakbary sorry I don't have a way to submit this otherwise, but in wazero we collected a lot of docs which we couldn't put upstream because there was no interest in changing them. Is there a place we can help contribute some missing detailed content? Like this https://github.com/tetratelabs/wazero/blob/main/imports/wasi_snapshot_preview1/args.go#L12-L44

If so, please ping me where as I'd really love the ABI everyone use to have the best docs, and those not being held hostage to source notes.

**Pull request merged**
